# Generated by Django 4.2.1 on 2023-05-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
