# Generated by Django 4.2.1 on 2023-06-02 07:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_gender_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gender',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country_code', models.CharField(max_length=5, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
                'permissions': (('can_view_gender', 'Can view gender'), ('can_add_gender', 'Can add gender'), ('can_edit_gender', 'Can edit gender'), ('can_delete_gender', 'Can delete gender')),
                'default_related_name': 'countries',
                'indexes': [models.Index(fields=['id', 'name'], name='users_count_id_5e7913_idx')],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='cor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.country', verbose_name='country_of_origin'),
        ),
    ]
