# Generated by Django 4.2.1 on 2023-06-02 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_id_alter_customuser_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'default_related_name': 'users', 'ordering': ['-created_at'], 'permissions': (('can_view_user', 'Can view user'), ('can_add_user', 'Can add user'), ('can_edit_user', 'Can edit user'), ('can_delete_user', 'Can delete user')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
