# Generated by Django 4.2.1 on 2023-06-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'default_related_name': 'countries', 'ordering': ['name'], 'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'default_related_name': 'users', 'ordering': ['-created_at'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='users_custo_id_cb84dd_idx',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ratings',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['id', 'email', 'phone_number', 'is_online'], name='users_custo_id_7a7cae_idx'),
        ),
    ]
