# Generated by Django 4.2.1 on 2023-06-02 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_gender_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'default_related_name': 'users', 'ordering': ['-created_at'], 'permissions': (('can_change_ratings_user', 'Can edit user'),), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
