# Generated by Django 4.2.1 on 2023-06-17 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together=set(),
        ),
    ]
