# Generated by Django 4.2.1 on 2023-06-18 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genders', '0001_initial'),
        ('countries', '0001_initial'),
        ('users', '0013_alter_customuser_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='countries.country', verbose_name='country_of_origin'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='genders.gender'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
